services:
  nrf54-dev:
    image: nrf54-dev
    container_name: nrf54-dev
    privileged: true
    volumes:
      - ./projects:/workspace/projects
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
    stdin_open: true
    tty: true
    working_dir: /workspace
